
-- Create a table for public profiles
create table if not exists users (
  uid uuid not null primary key,
  name text,
  email text,
  phone text,
  role text default 'Applicant',
  din text,
  created_at timestamptz default now()
);

-- Create a table for applications
create table if not exists applications (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users not null,
    type text not null,
    applicant_name text not null,
    status text not null default 'Pending',
    data jsonb,
    rejection_reason text,
    created_at timestamptz default now()
);

-- Create a table for tracking payments
create table if not exists payments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users not null,
  application_id bigint references applications,
  amount numeric(10, 2) not null,
  status text not null default 'Pending', -- e.g., Pending, Paid, Failed
  description text,
  transaction_ref text,
  provider text, -- e.g., Paystack, Stripe
  created_at timestamptz default now()
);
comment on table payments is 'Tracks user payments for applications and other services.';

-- Create a table for contact form submissions
create table if not exists contact_messages (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null,
  subject text,
  message text not null,
  is_read boolean default false,
  created_at timestamptz default now()
);
comment on table contact_messages is 'Stores messages submitted through the contact form.';


-- Set up Row Level Security (RLS)
-- USERS table
alter table users enable row level security;
create policy "Public profiles are viewable by everyone." on users for select using (true);
create policy "Users can insert their own profile." on users for insert with check (auth.uid() = uid);
create policy "Users can update their own profile." on users for update using (auth.uid() = uid);

-- APPLICATIONS table
alter table applications enable row level security;
create policy "Users can view their own applications." on applications for select using (auth.uid() = user_id);
create policy "Users can insert their own applications." on applications for insert with check (auth.uid() = user_id);

-- PAYMENTS table
alter table payments enable row level security;
create policy "Users can view their own payments." on payments for select using (auth.uid() = user_id);
create policy "Users can create their own payments." on payments for insert with check (auth.uid() = user_id);

-- This function is triggered when a new user signs up.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.users (uid, name, email, phone)
  values (
    new.id,
    new.raw_user_meta_data->>'full_name',
    new.email,
    new.phone
  );
  return new;
end;
$$;

-- Trigger the function after a new user is created
create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Create storage bucket for application documents
insert into storage.buckets (id, name, public)
values ('application_documents', 'application_documents', false)
on conflict (id) do nothing;

-- RLS policies for storage
create policy "Users can upload to their own folder."
on storage.objects for insert with check (
  bucket_id = 'application_documents' and
  auth.uid()::text = (storage.foldername(name))[1]
);

create policy "Users can view their own documents."
on storage.objects for select using (
  bucket_id = 'application_documents' and
  auth.uid()::text = (storage.foldername(name))[1]
);
