
-- Create the table for contact form submissions
CREATE TABLE IF NOT EXISTS public.contact_messages (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    name text,
    email text,
    subject text,
    message text,
    is_read boolean DEFAULT false,
    CONSTRAINT contact_messages_pkey PRIMARY KEY (id)
);

-- Add comments to the table and columns
COMMENT ON TABLE public.contact_messages IS 'Stores messages submitted through the public contact form.';
COMMENT ON COLUMN public.contact_messages.is_read IS 'Tracks if an admin has reviewed the message.';

-- Enable Row Level Security
ALTER TABLE IF EXISTS public.contact_messages
    ENABLE ROW LEVEL SECURITY;

-- Grant usage on the sequence to authenticated and anonymous users
GRANT USAGE, SELECT ON SEQUENCE contact_messages_id_seq TO anon, authenticated;

-- Allow public users (anonymous) to insert their own messages
CREATE POLICY "Allow public insert for contact messages"
    ON public.contact_messages
    FOR INSERT
    WITH CHECK (true);

-- Allow admins to see all messages
CREATE POLICY "Allow admin full access on contact messages"
    ON public.contact_messages
    FOR ALL
    TO service_role;

-- A more specific policy would be to allow admins (based on a custom role) to read/update/delete
-- This requires a 'users' table with a 'role' column. Assuming that exists from previous context:
CREATE POLICY "Allow admin users to manage contact messages"
    ON public.contact_messages
    FOR ALL
    USING ( (SELECT role FROM public.users WHERE uid = auth.uid()) = 'Admin' )
    WITH CHECK ( (SELECT role FROM public.users WHERE uid = auth.uid()) = 'Admin' );

