-- Drop existing transactions table if it exists to recreate with correct schema
DROP TABLE IF EXISTS public.transactions CASCADE;

-- Create transactions table
-- Note: application_id is TEXT to avoid type conflicts with the applications table
CREATE TABLE public.transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    application_id TEXT,
    amount DECIMAL(12, 2) NOT NULL,
    description TEXT,
    payment_reference TEXT UNIQUE NOT NULL,
    status TEXT DEFAULT 'Pending',
    payer_name TEXT,
    payer_email TEXT,
    payer_phone TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    last_verified_at TIMESTAMPTZ
);

-- Enable Row Level Security
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;

-- Policies
-- Allow users to view their own transactions
CREATE POLICY "Allow users to view own transactions"
ON public.transactions FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

-- Allow users to insert their own transactions
CREATE POLICY "Allow users to insert own transactions"
ON public.transactions FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

-- Allow users to update their own transactions
CREATE POLICY "Allow users to update own transactions"
ON public.transactions FOR UPDATE
TO authenticated
USING (auth.uid() = user_id);

-- Grant access to authenticated users
GRANT ALL ON public.transactions TO authenticated;
GRANT ALL ON public.transactions TO service_role;
