-- Create transactions table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    application_id TEXT,
    amount DECIMAL(12, 2) NOT NULL,
    description TEXT,
    payment_reference TEXT UNIQUE NOT NULL,
    status TEXT DEFAULT 'Pending',
    payer_name TEXT,
    payer_email TEXT,
    payer_phone TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    last_verified_at TIMESTAMPTZ
);

-- Add payment_link column to transactions table if it doesn't exist
ALTER TABLE public.transactions ADD COLUMN IF NOT EXISTS payment_link TEXT;

-- Ensure RLS is enabled
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;

-- Add policies if they don't exist (using DO block to avoid errors if they already exist)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow users to view own transactions') THEN
        CREATE POLICY "Allow users to view own transactions" ON public.transactions FOR SELECT TO authenticated USING (auth.uid() = user_id);
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow users to insert own transactions') THEN
        CREATE POLICY "Allow users to insert own transactions" ON public.transactions FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow users to update own transactions') THEN
        CREATE POLICY "Allow users to update own transactions" ON public.transactions FOR UPDATE TO authenticated USING (auth.uid() = user_id);
    END IF;
END
$$;

-- Grant access
GRANT ALL ON public.transactions TO authenticated;
GRANT ALL ON public.transactions TO service_role;
